services:
  db:
    image: postgres:17-alpine
    container_name: ${DB_CONTAINER_NAME}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_EXPOSED_PORT}:${POSTGRES_PORT}"
    volumes:
      - init_db_data:/var/lib/postgresql/data
      - ./init-DB/db-export:/docker-entrypoint-initdb.d:ro
    restart: unless-stopped
    networks:
      - init_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  backend:
    build:
      context: ./init-API
      dockerfile: Dockerfile
    container_name: ${BACKEND_CONTAINER_NAME}
    env_file:
      - ./init-API/.env
    environment:
      NODE_ENV: production
      PORT: ${BACKEND_PORT}
      DB_HOST: db
      DB_PORT: ${POSTGRES_PORT}
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    restart: unless-stopped
    networks:
      - init_net
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:${BACKEND_PORT}/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  # frontend:
  #   build:
  #     context: ./area_web
  #     dockerfile: Dockerfile
  #     args:
  #       # URL API vue par le navigateur (clearnet/Tor via le mÃªme endpoint)
  #       NEXT_PUBLIC_API_URL: http://localhost:8080
  #   container_name: area_web
  #   environment:
  #     NODE_ENV: production
  #     # URL API vue par le container (SSR / RSC)
  #     API_URL: http://backend:8080
  #   depends_on:
  #     backend:
  #       condition: service_healthy
  #   ports:
  #     - "8081:3000"
  #   restart: unless-stopped
  #   networks:
  #     - area_net
  #   healthcheck:
  #     test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000 || exit 1"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3

networks:
  init_net:
    driver: bridge

volumes:
  init_db_data:
